spring:
  ai:
    openai:
      base-url: http://localhost:1234
      api-key: "dummy"
      chat:
        options:
          model: google/gemma-3-4b
          temperature: 0.7
          stream-usage: true